AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM template with a simple API definition
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowHeaders: "'*'"
        AllowOrigin: "'http://localhost:3000'"
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Handler: bin/api
      Runtime: go1.x
Transform: AWS::Serverless-2016-10-31
